### ISSUE TITLE
How do I support both IPv4 and IPv6 connections?

### ISSUE THREAD

**Issue by SisMaker** [emqx/esockd#143]
I have a question: the project says that it supports IPv6, so how can gen_tcp be set to support both IPv4 and IPv6 connections?

**Comment by HJianBo** [comment]
Yes it is. Just explicitly set the inet6 option:

 e.g:
```
esockd:open(test, 3334, [{tcp_options, [inet6]}], {your_callback_module, start_link, []}).
```

**Comment by SisMaker** [comment]
> Yes it is. Just explicitly set the inet6 option:
> 
> e.g:
> 
> ```
> esockd:open(test, 3334, [{tcp_options, [inet6]}], {your_callback_module, start_link, []}).
> ```

thanks you very much, i will try it !

**Comment by SisMaker** [comment]
> > Yes it is. Just explicitly set the inet6 option:
> > e.g:
> > ```
> > esockd:open(test, 3334, [{tcp_options, [inet6]}], {your_callback_module, start_link, []}).
> > ```
> 
> thanks you very much, i will try it !

and i have some other questions the inet document say  ''{ipv6_v6only, Boolean}
Restricts the socket to use only IPv6, prohibiting any IPv4 connections. This is only applicable for IPv6 sockets (option inet6).

On most platforms this option must be set on the socket before associating it to an address. It is therefore only reasonable to specify it when creating the socket and not to use it when calling function (setopts/2) containing this description.

The behavior of a socket with this option set to true is the only portable one. The original idea when IPv6 was new of using IPv6 for all traffic is now not recommended by FreeBSD (you can use {ipv6_v6only,false} to override the recommended system default value), forbidden by OpenBSD (the supported GENERIC kernel), and impossible on Windows (which has separate IPv4 and IPv6 protocol stacks). Most Linux distros still have a system default value of false. This policy shift among operating systems to separate IPv6 from IPv4 traffic has evolved, as it gradually proved hard and complicated to get a dual stack implementation correct and secure.

On some platforms, the only allowed value for this option is true, for example, OpenBSD and Windows. Trying to set this option to false, when creating the socket, fails in this case.

Setting this option on platforms where it does not exist is ignored. Getting this option with getopts/2 returns no value, that is, the returned list does not contain an {ipv6_v6only,_} tuple. On Windows, the option does not exist, but it is emulated as a read-only option with value true.

Therefore, setting this option to true when creating a socket never fails, except possibly on a platform where you have customized the kernel to only allow false, which can be doable (but awkward) on, for example, OpenBSD.

If you read back the option value using getopts/2 and get no value, the option does not exist in the host operating system. The behavior of both an IPv6 and an IPv4 socket listening on the same port, and for an IPv6 socket getting IPv4 traffic is then no longer predictable."  Will this option disallow IPv4 connections on Windows?

**Comment by HJianBo** [comment]
> Will this option disallow IPv4 connections on Windows?

Agree that. But I haven't tested it, so maybe you can try to see if the actual situation is what the documentation says.

> On some platforms, the only allowed value for this option is true, for example, OpenBSD and Windows. 

>  On Windows, the option does not exist, but it is emulated as a read-only option with value true.

**Comment by SisMaker** [comment]
> > Will this option disallow IPv4 connections on Windows?
> 
> Agree that. But I haven't tested it, so maybe you can try to see if the actual situation is what the documentation says.
> 
> > On some platforms, the only allowed value for this option is true, for example, OpenBSD and Windows.
> 
> > On Windows, the option does not exist, but it is emulated as a read-only option with value true.

ok, thank you very much!
