### ISSUE TITLE
Proxy Protocol does not work with ssl

### ISSUE THREAD

**Issue by akshath27188** [emqx/esockd#91]
a)I have tested ssl example, connection with my custom key, cert which seems to be receiving data fine ,
b)I have also tested proxy protocol example and I receive the data from the socket after connection,
Problem - 
Tried adding the option {connopts, [proxy_protocol, {proxy_protocol_timeout, 1000}]} to the ssl example,
but connection seems to be failing.

**Comment by Gilbert-Wong** [comment]
Which esockd version did you use? And Which proxy protocol did you use? Please provide more details which help us reproduce the problem you encountered.

**Comment by akshath27188** [comment]
Hi Gilbert,
a)I did a clone on the master branch of esockd.
b)I am using erlang otp 19 (erts-8.1) 
c) I have attached the ssl example file that I had modified to use as proxy protocol
d) I have also attached my haproxy config file.

[haproxy.cfg.txt](https://github.com/emqx/esockd/files/2541443/haproxy.cfg.txt)
[ssl_echo_server.erl.txt](https://github.com/emqx/esockd/files/2541445/ssl_echo_server.erl.txt)

**Comment by turtleDeng** [comment]
@akshath27188 
```
	server rserve1 192.168.21.223:4001 check send-proxy-v2
```

```
    server rserve1 192.168.21.223:4001 check check-send-proxy send-proxy-v2-ssl-cn
```
