### ISSUE TITLE
Is esockd_connection_sup a supervisor or a gen_server

### ISSUE THREAD

**Issue by zhaoweiguo** [emqx/esockd#92]
%% start child
{ok, ConnSup} = supervisor:start_child(Sup,
		{connection_sup,
			{esockd_connection_sup, start_link, [Options, MFArgs, Logger]},
				transient, infinity, supervisor, [esockd_connection_sup]})

% % but, esockd_connection_sup is a gen_server
-module(esockd_connection_sup).
-behaviour(gen_server).

So, Is it a bug or for some special purpose?

**Comment by Gilbert-Wong** [comment]
No bug, no special purpose, you should learn more about OTP program style.
